[project]
name = "pybravo"
version = "0.1.0"
authors = [
    {name = "Silvio Ortiz Aburto"},
]
description = "Python driver with lower level control to Bravo liquid handler"
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.8"